apiVersion: apps/v1
kind: Deployment
metadata:
  name: app001
spec:
  selector:
    matchLabels:
      app: app001
  replicas: 2 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: app001
    spec:
      containers:
      - name: app001
        image: ranfangxu/app001
        ports:
        - containerPort: 8000

